instruments: 
    ivvi:
        type: qcodes_contrib_drivers.drivers.QuTech.IVVI
        address: COM6

        init:
            numdacs: 16
            polarity: ['BIP', 'BIP', 'BIP', 'NEG']
            use_locks: false
            dac_step: 1
            dac_delay: 0.1

        # add_parameters:     
            
        #     S: {source: dac3, label: Source Ohmic Gate, unit: V,scale: 1,step: 1.0e-3,initial_value: 0.}
        
        #     STL: {source: dac5, label: Lead Gate (L), unit: V,scale: 1,step: 1.0e-3,initial_value: 0.}
            
        #     LB: {source: dac6, label: Barrier Gate (L), unit: V,scale: 1,step: 1.0e-3,initial_value: 0.}
            
        #     P: {source: dac7, label: Plunger Gate, unit: V,scale: 1,step: 1.0e-3,initial_value: 0.}
            
        #     RB: {source: dac8, label: Barrier Gate (R), unit: V,scale: 1,step: 1.0e-3, initial_value: 0.}
            
        #     STR: {source: dac9, label: Lead Gate (R), unit: V,scale: 1,step: 1.0e-3,initial_value: 0.}
                  
    keithley2000:
        type: qcodes.instrument_drivers.Keithley.Keithley_2000.Keithley2000
        address: GPIB0::17::INSTR

        parameters:

            mode: {initial_value: 'dc voltage'}
        
        add_parameters:

            volt: {source: amplitude}

    sim900:
        type: qcodes_contrib_drivers.drivers.StanfordResearchSystems.SIM928.SIM928
        address: GPIB0::3::INSTR

        # add_parameters:     
        #     {
        #         S: {source: volt_8, label: Source Ohmic Gate,unit: V,scale: 1,initial_value: 0.},
        #         S_step: {source: volt_8_step, unit: V, initial_value: 0.01},
               
        #         STL: {source: volt_2, label: Lead Gate (L),unit: V,scale: 1,initial_value: 0.},
        #         STL_step: {source: volt_2_step, unit: V, initial_value: 0.01},
               
        #         LB: {source: volt_3, label: Barrier Gate (L),unit: V,scale: 1,initial_value: 0.},
        #         LB_step: {source: volt_3_step, unit: V, initial_value: 0.01},
               
        #         P: {source: volt_4, label: Plunger Gate,unit: V,scale: 1,initial_value: 0.},
        #         P_step: {source: volt_4_step, unit: V, initial_value: 0.01},
               
        #         RB: {source: volt_5, label: Barrier Gate (R),unit: V,scale: 1,initial_value: 0.},
        #         RB_step: {source: volt_5_step, unit: V, initial_value: 0.01},
               
        #         STR: {source: volt_6, label: Lead Gate (R),unit: V,scale: 1,initial_value: 0.},
        #         STR_step: {source: volt_6_step, unit: V, initial_value: 0.01},
        #     }

    agilent:
        type: qcodes.instrument_drivers.agilent.Agilent_34401A.Agilent34401A
        address: GPIB0::21::INSTR

    